edit.go

see: https://github.com/jesseduffield/lazygit/pull/1119

fix a bug related to inserting and deleting wide characters

---

gui.go

Sometimes I need a flag to hide footer of panels with lists, it's a footer with message '... of ...' in the right bottom coner of panel.

ShowTotal flag

---

gui.go
view.go

fix https://github.com/jesseduffield/lazygit/issues/2048

fix subtitle collision

---

view.go

<table>
<tr>
<td>before
<td><img width="316" alt="スクリーンショット 2022-08-26 18 39 36" src="https://user-images.githubusercontent.com/10097437/186876955-7875f713-cfae-465a-83d6-099b65094656.png">
<tr>
<td>after
<td><img width="293" alt="スクリーンショット 2022-08-26 18 40 05" src="https://user-images.githubusercontent.com/10097437/186877010-9ee1c5fe-45e8-4b28-bdcb-0734e8cc9c7d.png">
</table>

fix: improve hard tab rendering

---

escape.go
view.go

fix https://github.com/jesseduffield/lazygit/issues/2176
<table>
<tr>
<td>before
<td><img width="379" alt="スクリーンショット 2022-09-27 20 04 49" src="https://user-images.githubusercontent.com/10097437/192510070-73c49751-cfcd-45db-bbc4-c68070d6c1fc.png">
<td><img width="332" alt="スクリーンショット 2022-09-27 20 05 30" src="https://user-images.githubusercontent.com/10097437/192510112-77cb67e1-5be0-41ae-9ad1-48d7adff0c78.png">
<tr>
<td>after
<td><img width="370" alt="スクリーンショット 2022-09-27 20 04 38" src="https://user-images.githubusercontent.com/10097437/192510140-6e117a63-91e3-4f68-a70e-b3a7609c728a.png">
<td><img width="402" alt="スクリーンショット 2022-09-27 20 05 20" src="https://user-images.githubusercontent.com/10097437/192510189-3eb3820c-9609-4e66-8cc7-98d3b4802554.png">
</table>

Support ANSI reset sequence

---

edit.go
text_area.go
text_area_test.go

```
[aaa bbb!!!|]
↓ alt+left
[aaa bbb|!!!]
↓ alt+left
[aaa |bbb!!!]
↓ alt+left
[|aaa bbb!!!]
↓ alt+right
[aaa| bbb!!!]
↓ alt+right
[aaa bbb|!!!]
↓ alt+right
[aaa bbb!!!|]
```

Navigate by word using alt+left/right.

---

escape.go

Ignore OSC escape sequence (`\x1b]...\x1b\\`) https://github.com/jesseduffield/lazygit/discussions/2250
```yaml
git:
paging:
pager: delta --paging=never --hyperlinks
```
before:
after:

Ignore OSC sequence

---

gui.go

to resolve https://github.com/jesseduffield/lazygit/issues/1502

change StartTicking to receive ctx

---

gui.go

fix subtitle position

---

tcell_driver.go

Add support new border
refer to https://github.com/jesseduffield/lazygit/pull/2344

changes to support new borders

---

view.go

fix search with multibyte characters

---

gui.go
view.go

maybe related to https://github.com/jesseduffield/lazygit/issues/2420

prevent data race in `CopyContent`

---

view.go

Adding a couple mutexes to avoid a race condition

use mutexes to avoid race condition

---

view.go

Code was reviewed as part of https://github.com/jesseduffield/lazygit/pull/2915, please see there for more information.

Jump to middle of the view when selection leaves the visible area

---

gui.go
view.go

Code was reviewed as part of https://github.com/jesseduffield/lazygit/pull/2993.

Add TitlePrefix

---

.github/workflows/ci.yml
gui.go
scrollbar.go

See https://github.com/jesseduffield/lazygit/issues/1924
Also adds a CI job for unit tests

Use slimmer scrollbars

---

text_area.go
text_area_test.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/3173, taken unchanged from there.

Add auto-wrap support to TextArea

---

escape.go
escape_test.go
gui.go
gui_others.go
gui_windows.go
keybinding.go
view.go

This was reviewed as part of https://github.com/jesseduffield/lazygit/pull/3502, except for a few commits that I added to fix some linter warnings that I keep seeing in VS Code, and that I find annoying. These should be obvious enough that they don't need much of a review.

Add ErrorHandler

---

view.go

Needed for https://github.com/jesseduffield/lazygit/pull/3667, and reviewed as part of that.

Add view properties HighlightInactive and InactiveViewSelBgColor

---

view.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/3839.

Make ViewLinesHeight method more reliable

---

gui.go
tcell_driver.go
view.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/3856.

Underline hyperlinks on mouse hover

---

gui.go
view.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/3890.

Reduce error handling

---

gui.go

Handlers can return this to signal that they didn't handle the key and it should be dispatched further.
Reviewed as part of https://github.com/jesseduffield/lazygit/pull/4554.

Add ErrKeybindingNotHandled
