jesseduffield/gocui

gui.go

Visually this looks just a bit better,  
Now the 1 line boxes have the same width as the normal boxes.
See https://github.com/jesseduffield/lazygit/pull/441#issuecomment-487065334 for more information

Added `╴` and `╶` to the side of boxes when 1 height

---

gui.go
keybinding.go

This PR is made after a comment from you on: https://github.com/jesseduffield/lazygit/pull/441  
This PR solves: 
- `*errors.errorString` when resizing lg to a supper small size
- `panic: runtime error: invalid memory address or nil pointer dereference` when lazygit never renders UI only the to small box and someone presses a key

Fix lazygit small size panics

---

gui.go
gui_notwin.go
gui_win.go

Moved non-Windows code to new non-Windows file so gocui can continue being built on Windows.

Move non-Windows code behind build tags

---

gui.go

`LANG=zh lazygit`
|  | before | after  |
|--|--------|--------|
|stash and commands| <img width="1606" alt="スクリーンショット 2021-08-18 22 04 36" src="https://user-images.githubusercontent.com/10097437/129903404-4abd8ee2-c7fc-4c0c-a713-f1b18a13df2e.png">|<img width="1609" alt="スクリーンショット 2021-08-18 22 07 04" src="https://user-images.githubusercontent.com/10097437/129903483-2a35d731-cdbe-4ef9-b402-af956e0badc2.png">|
|commit message| <img width="198" alt="スクリーンショット 2021-08-18 22 04 44" src="https://user-images.githubusercontent.com/10097437/129903548-a6aaa1ef-f145-4e24-9d3b-08831b9e93e7.png"> |<img width="210" alt="スクリーンショット 2021-08-18 22 04 08" src="https://user-images.githubusercontent.com/10097437/129903562-7e6c5c1f-2014-4522-b6d9-2f1709ad1d92.png">|
```go
for i, ch := range str {
```
When we …

Fix rendering of view titles containing multi-byte char

---

view.go

before:
after:
@jesseduffield This patch is dirty, so I would like to hear your opinion.

Fix line wrapping when combining wide characters with eraseInLineFromCursor.

---

edit.go
text_area.go
text_area_test.go

And fix panic when pressing backspace on start of the second line. https://github.com/jesseduffield/lazygit/issues/1345
```
[This is Test|  ]
↓ c-w
[This is |      ]
↓ c-w
[This |         ]
```
referred: https://github.com/jesseduffield/lazygit/pull/1142

Add Ctrl+W keybind to delete word like shell

---

view.go

The cursor shifts by the number of wide characters off the screen.
<table>
<tr>
<th>action
<th>before (awesome)
<th>after
<tr>
<th>-
<td><img width="530" alt="スクリーンショット 2021-10-30 22 15 40" src="https://user-images.githubusercontent.com/10097437/139534321-e7914a9e-b04c-48a0-b60d-a0defb446ec2.png">
<td>
<tr>
<th>type "a"
<td>
<td>
<tr>
<th>type "b"
<td>
<td>
<tr>
<th>type "c"
<td>
<td>
</table>

Fix an issue where long inputs containing wide characters cause blank spaces on the right side.

---

gui.go

for https://github.com/jesseduffield/lazygit/pull/2161

allow nil in keybindings

---

gui.go

`g.stop <- struct{}{}` can only interrupt one `<-g.stop`.

fix goroutine leak

---

attribute.go
escape.go
escape_test.go
gui_others.go
gui_windows.go

fix https://github.com/jesseduffield/lazygit/issues/1831
This is because escape codes such as `\e[1;95;48;2;255;224;224m` (`1`: bold, `95`: fg light magenta, `48;2;255;224;224`: bg `#ffe0e0`) cannot be interpreted.
```ini
[core]
pager = delta
[delta]
line-numbers = true
[diff]
colorMoved = default
colorMovedWS = allow-indentation-change
[color "diff"]
; oldMoved = bold brightmagenta "#ffe0e0"
; oldMovedAlternative = bold brightmagenta "#ffe0e0"
oldMoved = bold brightmagenta brightblack
oldMovedAlternative = bold brightmagenta brightblack
newMoved = bold brightblue "#d0ffd0"
newMovedAlternative = bold brightblue "#d0ffd0"
```
1. `git diff`:
<table>
<tr>
<td>before
<td>after
<tr>
<td>
<td>
</table>
2. https://github.com/Ryooooooga/dotfiles/blob/942aa62f8d8d4e90ecf2fee8bd3bc0e26654f576/config …

fix escape codes

---

gui.go
tcell_driver.go

Now that we're using the new integration test pattern we can strip out some old code

Remove old recording stuff

---

view.go

Needed for https://github.com/jesseduffield/lazygit/pull/3642, and reviewed as part of it.

Support searching the model instead of the view

---

view.go

Needed for https://github.com/jesseduffield/lazygit/pull/2533, and reviewed as part of it.

Add functions SetContentLineCount and OverwriteLinesAndClearEverythingElse

---

gui.go

Needed for https://github.com/jesseduffield/lazygit/pull/3694, and reviewed as part of it.

Re-render text area of editable views when view size changes

---

view.go

Reviewed in https://github.com/jesseduffield/lazygit/pull/3783.

Clear viewLines when calling overwriteLines

---

view.go

Reviewed in https://github.com/jesseduffield/lazygit/pull/3820.

Fix eraseInLineFromCursor implementation

---

gui.go

Preparations for https://github.com/jesseduffield/lazygit/pull/3787, reviewed as part of that PR.

Allow changing mouse enabling while running

---

gui.go
text_area.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/3836.

Improve mouse handling in editable views

---

escape.go
gui.go
tcell_driver.go
view.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/3825.

Support hyperlinks

---

view.go

If ViewLinesHeight was called concurrently with drawing the view, the viewLines could be truncated.
Regression introduced in 3fd13166c9.

Fix a rendering regression introduced in #61

---

view.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/3914.

Add AutoRenderHyperLinks functionality to View

---

gui.go
view.go

This is a breaking change!
This fixes View.Size, Width and Height to be the correct (outer) size of a view including its frame, and InnerSize/InnerWidth/InnerHeight to be the usable client area exluding the frame. See commit message for details.
Reviewed as part of https://github.com/jesseduffield/lazygit/pull/4085.

Make view geometry a little more sane

---

view.go
view_test.go

This fixes a theoretical problem with overwriting existing lines where a line is exactly one character longer than what's being written; in this case we overwrite the existing character with a null character.
This is only a theoretical problem because to my knowledge we don't overwrite existing text anywhere, at least not in lazygit. The motivation of this PR was not so much to fix the bug, but to simplify the code; this makes it easier to put [this PR](https://github.com/jesseduffield/gocui/pull/69) on top of it.

Fix handling of `\n` wrt inserting null cells

---

view.go
view_test.go

If `writeString` or `writeRunes` is called with text ending in a newline character (which is very common), we currently insert an extra blank line at the bottom of the view, which doesn't look right. Avoid adding this extra line unless more text is added with another `writeString` call.
Sits on top of #68.

Avoid blank line at end of view

---

view.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/4182.

Only avoid the blank line at end of view if view is not editable

---

view.go

White text is hard to read on a cyan or yellow background, so using black improves contrast.
Fixes https://github.com/jesseduffield/lazygit/issues/4162.

Use black as the foreground color for highlighted search results

---

gui.go
tcell_driver.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/4234.

Support bracketed paste events

---

view.go

Reviewed as part of https://github.com/jesseduffield/lazygit/pull/4291.

Add a TabWidth field to gocui.View

---

view.go
view_test.go

Previously we would render hyperlinks only when seeing a newline; but for some views, the last line doesn't end in a newline (e.g. lazygit's confirmation panels), so hyperlinks were never rendered in the last line for those.

Render hyperlinks in last line of view if it doesn't end with a line feed

---

view.go

It seems that highlighting has so far only been used in cases where there wasn't a background color. Or'ing the bits of the color with the existing background color doesn't make sense.
Reviewed as part of https://github.com/jesseduffield/lazygit/pull/4429.

Make highlight overwrite the background color

---

gui.go

Return ErrKeybindingNotHandled to clients.
Reviewed as part of https://github.com/jesseduffield/lazygit/pull/4617.

Return ErrKeybindingNotHandled to clients
